### ISSUE TITLE
openconnect cannot be built with libressl

### ISSUE THREAD

**Issue by kapsh** [ony/exony#8]
When libressl set as provider openconnect fails to build with message 

```
checking for known-broken versions of OpenSSL... yes
configure: error: LibreSSL does not support Cisco DTLS.
Build with OpenSSL or GnuTLS instead.
```

[1522683103-install-net-apps_openconnect-7.08:0::exony.out.txt](https://github.com/ony/exony/files/1876815/1522683103-install-net-apps_openconnect-7.08.0.exony.out.txt)

I suggest to remove libressl from providers list for clarity so user can configure first instead of facing build fail.

**Comment by fkroener** [comment]
@kapsh did you actually test this change?

you'll need to remove it from dependencies as well.

**Comment by kapsh** [comment]
@fkroener thanks for spotting this — I really overlooked the warning about missing flag.

**Comment by fkroener** [comment]
there is no warning though - it will simply refuse to build.

**Comment by kapsh** [comment]
My bad. Would you kindly to check updated version in #12? Now it **actually** builds (at least with providers:gnutls on my rig).

**Comment by fkroener** [comment]
Looks good. Just one thing: you forgot to revbump - since dependencies changed this is required and would have helped you catching the error in the first place.

**Comment by kapsh** [comment]
I'll consider this in the future. Thanks.
